[tools]
ruby = "latest"
lazygit = "latest"

[tasks."rubocop:fix"]
description = "Fix RuboCop errors automatically"
run = [
    "bundle exec rubocop --autocorrect-all"
]

[tasks."rails:dev"]
description = "Run Rails in development mode"
run = [
    "bundle exec rails server"
]
