name: CI

on:
  pull_request:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security:
    name: Security Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run Brakeman security scan
        run: bin/brakeman --no-pager --format json --output brakeman-results.json

      - name: Upload Brakeman results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: brakeman-results
          path: brakeman-results.json

      - name: Scan JavaScript dependencies
        run: bin/importmap audit

  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run RuboCop
        run: bin/rubocop --format github --format json --out rubocop-results.json

      - name: Upload RuboCop results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: rubocop-results
          path: rubocop-results.json

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_type: [unit, system]
    
    steps:
      - name: Install system packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git libyaml-dev pkg-config google-chrome-stable

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Prepare test database
        env:
          RAILS_ENV: test
        run: bin/rails db:test:prepare

      - name: Run unit tests
        if: matrix.test_type == 'unit'
        env:
          RAILS_ENV: test
        run: bin/rails test --verbose

      - name: Run system tests
        if: matrix.test_type == 'system'
        env:
          RAILS_ENV: test
        run: bin/rails test:system --verbose

      - name: Upload test coverage
        if: matrix.test_type == 'unit'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
          if-no-files-found: ignore

      - name: Upload system test screenshots
        if: matrix.test_type == 'system' && failure()
        uses: actions/upload-artifact@v4
        with:
          name: system-test-screenshots
          path: tmp/screenshots/
          if-no-files-found: ignore

  build:
    name: Build Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Precompile assets
        env:
          RAILS_ENV: production
          SECRET_KEY_BASE: test-key-for-asset-compilation
        run: bin/rails assets:precompile

      - name: Verify application loads
        env:
          RAILS_ENV: production
          SECRET_KEY_BASE: test-key-for-asset-compilation
        run: timeout 30s bin/rails runner "puts 'Application loaded successfully'"
